PATHS:
  dist: "./public/dist"
  assets:
    images: "./src/assets/images/*/*"
    fonts: "./src/assets/fonts/*"
  vendor:
    - "./src/assets/vendor/jquery/jquery.js"
    - "./src/assets/vendor/bootstrap/js/bootstrap.bundle.js"
    - "./src/assets/vendor/jquery-easing/jquery.easing.js"
  javascript:
    - "./src/assets/javascript/jqBootstrapValidation.js"
    - "./src/assets/javascript/contact_me.js"
    - "./src/assets/javascript/agency.js"
    - "./src/assets/javascript/slick.js"
    - "./src/assets/javascript/slick_setup.js"
    - "./src/assets/javascript/jquery.lazy.js"
    - "./src/assets/javascript/lazy-loading.js"
  stylesheet:
    vendor:
      - "./src/assets/vendor/bootstrap/css/bootstrap.css"
      - "./src/assets/vendor/fontawesome-free/css/all.css"
    css:
      - "./src/assets/scss/agency.scss"