PATHS:
  dist: "./public/dist"
  assets:
    images: "./src/assets/images/*/*"
    fonts: "./src/assets/fonts/*"
  vendor:
    - "./src/assets/vendor/jquery/jquery.min.js"
  javascript:
    - "./src/assets/javascript/jqBootstrapValidation.js"
    - "./src/assets/javascript/contact_me.js"
    - "./src/assets/javascript/agency.js"
    - "./src/assets/javascript/appLibrary.js"
  stylesheet:
    bootstrapVendor:
      - "./src/assets/vendor/bootstrap/css/bootstrap.css"
    fontVendor:
      "./src/assets/vendor/fontawesome-free/css/all.min.css"
    css:
      - "./src/assets/scss/agency.scss"